[pytest]
# 1. Базовые опции запуска
addopts = --alluredir=allure-results -v -s --tb=short

# 2. Регистрация кастомных маркеров (чтобы Pytest не выдавал ворнинги)
markers =
    smoke: Критические тесты для быстрой проверки работоспособности (напр. логин)
    regression: Тесты полной регрессии функционала
    api: Тесты бэкенд эндпоинтов

# 3. Маска для поиска тестов (какие файлы считать тестами)
python_files = test_*.py
python_classes = Test*
python_functions = test_*
